name: Testing

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

env:
  GO111MODULE: "on"

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup environment variables
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo $(go env GOPATH)/bin >> $GITHUB_PATH
      shell: bash

    - name: Install order
      run: |
        go get -u github.com/DamianSkrzypczak/order
      shell: bash

    - name: Setup development environment
      run: |
        order setup-dev
      shell: bash

    - name: Run precommit checks
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        order precommit
      shell: bash
